#!/sbin/busybox sh

if [ "a${2}" == "a" ];
then
  echo "${soundgasm_sp}"
  exit
else
 soundgasm_sp="${2}"
 echo "${soundgasm_sp}" > /sys/devices/virtual/sound/sound_mc1n2/AVOL_SP
 echo "1" > /sys/devices/virtual/sound/sound_mc1n2/update_volume
fi

echo "${soundgasm_sp}"
