#!/sbin/busybox sh
#
cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

## Enable Logging??
mv /boot-debug.txt /boot-debug.BAK
date >/boot-debug.txt
exec >>/boot-debug.txt 2>&1

echo "Booting..."
echo "ENV-PATH: $PATH"


if grep -q bootmode=2 /proc/cmdline; then
  echo "Booting Recovery Mode ..."
  cp /recovery.rc /init.rc
  rm /init
  mv /innt /init
  exec /init
fi

if grep -q 1 /sys/class/power_supply/battery/batt_lp_charging; then
  echo "Booting low power mode ..."
  cp /lpm.rc /init.rc
  rm /init.smdk4210.rc
  rm /init
  mv /innt /init
  exec /init
fi

echo "Booting normal System Mode ..."
rm /init
mv /innt /init
exec /init
