#!/sbin/busybox sh
#
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

######################
## Enable Logging?? ##
mv /boot-log.txt /boot-log.bak
busybox date >/boot-log.txt
exec >>/boot-log.txt 2>&1
#
echo "Starting System ..."

tar xvf /res/misc/dev.tar

if grep -q bootmode=2 /proc/cmdline ; then
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp /recovery.rc /init.rc
  sed -i 's|found STOCK based System|Recovery BOOT|g' sbin/init.samsung
  exec /sbin/init.samsung
fi

if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp lpm.rc init.rc
  rm init.smdk4210.rc
  sed -i 's|found STOCK based System|LPM BOOT|g' sbin/init.samsung
  exec /sbin/init.samsung
fi

SECONDROM=1
NOBOOTLOGO=0
mount -t ext4 -o ro /dev/block/mmcblk0p12 /preload
mount -t vfat /dev/block/mmcblk0p11 /mnt/sdcard && ( touch /mnt/sdcard/clockworkmod/.nomedia )
mount -t vfat /dev/block/mmcblk1p1 /mnt/emmc && ( touch /mnt/emmc/clockworkmod/.nomedia )
[ -f /preload/build.prop ] || SECONDROM=0
[ -f /mnt/sdcard/.secondrom/data.img ] || SECONDROM=0
[ -f /mnt/sdcard/.secondrom/cache.img ] || SECONDROM=0
[ -f /mnt/sdcard/.nobootlogo ] && NOBOOTLOGO=1 && SECONDROM=0
umount /preload
umount /mnt/sdcard
umount /emmc

if [[ "$NOBOOTLOGO" == "1" && "$SECONDROM" == "0" ]];then
  /sbin/choose_rom
else
  /sbin/choose_rom $SECONDROM
fi

if [ "$?" == "1" ]; then
  SECONDROM=1
else
  SECONDROM=0
fi

/sbin/busybox mount -t ext4 /res/dev/system /system

if [ -f /system/recovery.cpio.gz ];
then
mount -o remount,rw /
zcat /system/recovery.cpio.gz | cpio -idmu
fi;

AOSP=0
MIUI=0
B2G=0
S4A=0
CM10=0
JELLY=0

[ -d /system/b2g ] && B2G=1
[ "`/sbin/busybox grep -i android-htc-rev /system/build.prop`" ] && S4A=1
[ -f /system/framework/framework2.jar ] || AOSP=1
[ "`/sbin/busybox grep Slim /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i aosp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i hydrog /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =aokp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i CyanogenMod /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i AdyScorpius /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i cMIUI /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i insanity /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i Oxygen /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =MIUI /system/build.prop`" ] && MIUI=1
[ -f /system/framework/framework-miui.jar ] && MIUI=1
[ -f /system/lib/ssl/engines/libkeystore.so ] && JELLY=1
[ -f /system/framework/seccamera.jar ] || CM10=1


## JellyBean (4.1.1) Support
if [ "$JELLY" == 1 ];
then
  if [ "$CM10" == 1 ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
    rm /sbin/init.samsung
    mv /sbin/init.cm10 /sbin/init.samsung
  else
    echo 0 > /proc/sys/kernel/rom_feature_set
    rm /sbin/init.samsung
    mv /sbin/init.jelly /sbin/init.samsung
  fi
else
  ## B2G Support
  if [ "$B2G" == 1 ];
  then
    rm /init.rc
    rm /init.rc.2
    cp /res/misc/init.b2g /init.rc
    cp /res/misc/init.b2g.2 /init.rc.2
    sed -i 's|STOCK|B2G|g' sbin/init.samsung
  fi;

  ## CM/AOSP Support
  if [ "$AOSP" == 1 ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
    rm /sbin/init.samsung
    mv /sbin/init.cm9 /sbin/init.samsung
  else
    rm /init.smdk4210.rc.2
    echo 0 > /proc/sys/kernel/rom_feature_set
  fi;

  ## MIUI Support
  if [ "$MIUI" == 1 ];
  then
    rm /init.rc
    rm /init.rc.2
    cp /res/misc/init.miui /init.rc
    cp /res/misc/init.miui.2 /init.rc.2
    cp /res/misc/default.prop.miui /default.prop
    sed -i 's|STOCK|MIUI|g' sbin/init.samsung
  fi

  ## S4A Support
  if [ "$S4A" == 1 ];
  then
    rm /init.rc
    rm /init.rc.2
    cp /res/misc/init.s4a /init.rc
    cp /res/misc/init.s4a.2 /init.rc.2
    sed -i 's|STOCK|Sense4All|g' sbin/init.samsung
  fi
fi

## SGH-i777 MIC Swap FIX
# EXPERIMENTAL !!
# We can fix the SGH-I777 Mic Swap Issue here

#uname -r | grep 'I777'
#
#if [ "$?" == "0" ];
#then
#  echo "Found I777 Machine Checking libaudio"
#  mount -o remount,rw /
#  xzcat /res/misc/libaudio.tar.xz > /tmp/libaudio.tar
#  mkdir /tmp/libaudio
#  cd /tmp/libaudio
#  tar xf ../libaudio.tar
#  LIBAUDIOMD51=`md5sum /system/lib/libmediayamaha.so`
#  LIBAUDIOMD52=`md5sum /tmp/libaudio/libmediayamaha.so`
#  if [ "a${LIBAUDIOMD51}" != "a${LIBAUDIOMD52}" ];
#  then
#    echo "Updating libaudio ..."
#    cp -ax /tmp/libaudio/* /system/lib/
#  else
#    echo "libaudio already up to date ..."
#  fi
#  rm -rf /tmp/libaudio /tmp/libaudio.tar /res/misc/libaudio.tar.xz
# cd /
#else
#  echo "no I777 Machine assuming GT-I9100"
#fi

busybox umount /system
exec /sbin/init.samsung $SECONDROM
